/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as UserRouteRouteImport } from "./routes/_user/route";
import { Route as CreateProfileRouteImport } from "./routes/create-profile";
import { Route as UserPublicRouteRouteImport } from "./routes/_user/_public/route";
import { Route as UserEraseUserRouteRouteImport } from "./routes/_user/erase-user/route";
import { Route as UserJobsRouteRouteImport } from "./routes/_user/jobs/route";
import { Route as UserManageRouteRouteImport } from "./routes/_user/manage/route";
import { Route as UserTeamsRouteRouteImport } from "./routes/_user/teams/route";
import { Route as UserPublicIndexRouteImport } from "./routes/_user/_public/index";
import { Route as UserAcceptHostInviteCodeRouteImport } from "./routes/_user/accept-host-invite.$code";
import { Route as UserAcceptTeamInviteCodeRouteImport } from "./routes/_user/accept-team-invite.$code";
import { Route as UserEraseUserIndexRouteImport } from "./routes/_user/erase-user/index";
import { Route as UserJobsListRouteRouteImport } from "./routes/_user/jobs/_list/route";
import { Route as UserManageIndexRouteImport } from "./routes/_user/manage/index";
import { Route as UserManageEditionIdRouteRouteImport } from "./routes/_user/manage/$editionId/route";
import { Route as UserManageCreateEditionRouteImport } from "./routes/_user/manage/create-edition";
import { Route as UserTeamsIndexRouteImport } from "./routes/_user/teams/index";
import { Route as UserPublicEditionsEditionIdRouteRouteImport } from "./routes/_user/_public/editions/$editionId/route";
import { Route as UserJobsListIndexRouteImport } from "./routes/_user/jobs/_list/index";
import { Route as UserJobsListJobIdRouteImport } from "./routes/_user/jobs/_list/$jobId";
import { Route as UserManageEditionIdIndexRouteImport } from "./routes/_user/manage/$editionId/index";
import { Route as UserManageEditionIdCustomFieldsRouteRouteImport } from "./routes/_user/manage/$editionId/custom-fields/route";
import { Route as UserManageEditionIdLocationsRouteRouteImport } from "./routes/_user/manage/$editionId/locations/route";
import { Route as UserManageEditionIdScheduleRouteRouteImport } from "./routes/_user/manage/$editionId/schedule/route";
import { Route as UserManageEditionIdSessionTypesRouteRouteImport } from "./routes/_user/manage/$editionId/session-types/route";
import { Route as UserManageEditionIdSessionsRouteRouteImport } from "./routes/_user/manage/$editionId/sessions/route";
import { Route as UserManageEditionIdSettingsRouteRouteImport } from "./routes/_user/manage/$editionId/settings/route";
import { Route as UserManageEditionIdSubmissionFormRouteRouteImport } from "./routes/_user/manage/$editionId/submission-form/route";
import { Route as UserManageEditionIdTracksRouteRouteImport } from "./routes/_user/manage/$editionId/tracks/route";
import { Route as UserManageEditionIdVenuesRouteRouteImport } from "./routes/_user/manage/$editionId/venues/route";
import { Route as UserTeamsEditTeamIdRouteImport } from "./routes/_user/teams/edit.$teamId";
import { Route as UserPublicEditionsEditionIdProfileRouteImport } from "./routes/_user/_public/editions/$editionId/profile";
import { Route as UserManageEditionIdCustomFieldsIndexRouteImport } from "./routes/_user/manage/$editionId/custom-fields/index";
import { Route as UserManageEditionIdCustomFieldsCreateRouteImport } from "./routes/_user/manage/$editionId/custom-fields/create";
import { Route as UserManageEditionIdHostsIndexRouteImport } from "./routes/_user/manage/$editionId/hosts/index";
import { Route as UserManageEditionIdHostsHostIdRouteImport } from "./routes/_user/manage/$editionId/hosts/$hostId";
import { Route as UserManageEditionIdLocationsIndexRouteImport } from "./routes/_user/manage/$editionId/locations/index";
import { Route as UserManageEditionIdLocationsCreateRouteImport } from "./routes/_user/manage/$editionId/locations/create";
import { Route as UserManageEditionIdScheduleIndexRouteImport } from "./routes/_user/manage/$editionId/schedule/index";
import { Route as UserManageEditionIdScheduleScheduleIdRouteImport } from "./routes/_user/manage/$editionId/schedule/$scheduleId";
import { Route as UserManageEditionIdSessionTypesListRouteRouteImport } from "./routes/_user/manage/$editionId/session-types/_list/route";
import { Route as UserManageEditionIdSessionsSessionIdRouteImport } from "./routes/_user/manage/$editionId/sessions/$sessionId";
import { Route as UserManageEditionIdSessionsListRouteRouteImport } from "./routes/_user/manage/$editionId/sessions/_list/route";
import { Route as UserManageEditionIdSessionsCreateRouteImport } from "./routes/_user/manage/$editionId/sessions/create";
import { Route as UserManageEditionIdSubmissionFormIndexRouteImport } from "./routes/_user/manage/$editionId/submission-form/index";
import { Route as UserManageEditionIdSubmissionFormMoreInfoRouteImport } from "./routes/_user/manage/$editionId/submission-form/more-info";
import { Route as UserManageEditionIdSubmissionFormProfileRouteImport } from "./routes/_user/manage/$editionId/submission-form/profile";
import { Route as UserManageEditionIdSubmissionFormSessionRouteImport } from "./routes/_user/manage/$editionId/submission-form/session";
import { Route as UserManageEditionIdTracksListRouteRouteImport } from "./routes/_user/manage/$editionId/tracks/_list/route";
import { Route as UserManageEditionIdVenuesIndexRouteImport } from "./routes/_user/manage/$editionId/venues/index";
import { Route as UserManageEditionIdVenuesCreateRouteImport } from "./routes/_user/manage/$editionId/venues/create";
import { Route as UserPublicEditionsEditionIdSessionsIndexRouteImport } from "./routes/_user/_public/editions/$editionId/sessions/index";
import { Route as UserPublicEditionsEditionIdSessionsCreateRouteImport } from "./routes/_user/_public/editions/$editionId/sessions/create";
import { Route as UserManageEditionIdCustomFieldsEditCustomFieldIdRouteImport } from "./routes/_user/manage/$editionId/custom-fields/edit.$customFieldId";
import { Route as UserManageEditionIdLocationsEditLocationIdRouteImport } from "./routes/_user/manage/$editionId/locations/edit.$locationId";
import { Route as UserManageEditionIdSessionTypesListIndexRouteImport } from "./routes/_user/manage/$editionId/session-types/_list/index";
import { Route as UserManageEditionIdSessionTypesListCreateRouteImport } from "./routes/_user/manage/$editionId/session-types/_list/create";
import { Route as UserManageEditionIdSessionsListIndexRouteImport } from "./routes/_user/manage/$editionId/sessions/_list/index";
import { Route as UserManageEditionIdTracksListIndexRouteImport } from "./routes/_user/manage/$editionId/tracks/_list/index";
import { Route as UserManageEditionIdTracksListCreateRouteImport } from "./routes/_user/manage/$editionId/tracks/_list/create";
import { Route as UserManageEditionIdVenuesEditVenueIdRouteImport } from "./routes/_user/manage/$editionId/venues/edit.$venueId";
import { Route as UserPublicEditionsEditionIdSessionsSessionIdIndexRouteImport } from "./routes/_user/_public/editions/$editionId/sessions/$sessionId/index";
import { Route as UserPublicEditionsEditionIdSessionsSessionIdEditRouteImport } from "./routes/_user/_public/editions/$editionId/sessions/$sessionId/edit";
import { Route as UserManageEditionIdSessionTypesListEditSessionTypeIdRouteImport } from "./routes/_user/manage/$editionId/session-types/_list/edit.$sessionTypeId";
import { Route as UserManageEditionIdTracksListEditTrackIdRouteImport } from "./routes/_user/manage/$editionId/tracks/_list/edit.$trackId";

const UserRouteRoute = UserRouteRouteImport.update({
  id: "/_user",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateProfileRoute = CreateProfileRouteImport.update({
  id: "/create-profile",
  path: "/create-profile",
  getParentRoute: () => rootRouteImport,
} as any);
const UserPublicRouteRoute = UserPublicRouteRouteImport.update({
  id: "/_public",
  getParentRoute: () => UserRouteRoute,
} as any);
const UserEraseUserRouteRoute = UserEraseUserRouteRouteImport.update({
  id: "/erase-user",
  path: "/erase-user",
  getParentRoute: () => UserRouteRoute,
} as any);
const UserJobsRouteRoute = UserJobsRouteRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => UserRouteRoute,
} as any);
const UserManageRouteRoute = UserManageRouteRouteImport.update({
  id: "/manage",
  path: "/manage",
  getParentRoute: () => UserRouteRoute,
} as any);
const UserTeamsRouteRoute = UserTeamsRouteRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => UserRouteRoute,
} as any);
const UserPublicIndexRoute = UserPublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => UserPublicRouteRoute,
} as any);
const UserAcceptHostInviteCodeRoute =
  UserAcceptHostInviteCodeRouteImport.update({
    id: "/accept-host-invite/$code",
    path: "/accept-host-invite/$code",
    getParentRoute: () => UserRouteRoute,
  } as any);
const UserAcceptTeamInviteCodeRoute =
  UserAcceptTeamInviteCodeRouteImport.update({
    id: "/accept-team-invite/$code",
    path: "/accept-team-invite/$code",
    getParentRoute: () => UserRouteRoute,
  } as any);
const UserEraseUserIndexRoute = UserEraseUserIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => UserEraseUserRouteRoute,
} as any);
const UserJobsListRouteRoute = UserJobsListRouteRouteImport.update({
  id: "/_list",
  getParentRoute: () => UserJobsRouteRoute,
} as any);
const UserManageIndexRoute = UserManageIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => UserManageRouteRoute,
} as any);
const UserManageEditionIdRouteRoute =
  UserManageEditionIdRouteRouteImport.update({
    id: "/$editionId",
    path: "/$editionId",
    getParentRoute: () => UserManageRouteRoute,
  } as any);
const UserManageCreateEditionRoute = UserManageCreateEditionRouteImport.update({
  id: "/create-edition",
  path: "/create-edition",
  getParentRoute: () => UserManageRouteRoute,
} as any);
const UserTeamsIndexRoute = UserTeamsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => UserTeamsRouteRoute,
} as any);
const UserPublicEditionsEditionIdRouteRoute =
  UserPublicEditionsEditionIdRouteRouteImport.update({
    id: "/editions/$editionId",
    path: "/editions/$editionId",
    getParentRoute: () => UserPublicRouteRoute,
  } as any);
const UserJobsListIndexRoute = UserJobsListIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => UserJobsListRouteRoute,
} as any);
const UserJobsListJobIdRoute = UserJobsListJobIdRouteImport.update({
  id: "/$jobId",
  path: "/$jobId",
  getParentRoute: () => UserJobsListRouteRoute,
} as any);
const UserManageEditionIdIndexRoute =
  UserManageEditionIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdCustomFieldsRouteRoute =
  UserManageEditionIdCustomFieldsRouteRouteImport.update({
    id: "/custom-fields",
    path: "/custom-fields",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdLocationsRouteRoute =
  UserManageEditionIdLocationsRouteRouteImport.update({
    id: "/locations",
    path: "/locations",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdScheduleRouteRoute =
  UserManageEditionIdScheduleRouteRouteImport.update({
    id: "/schedule",
    path: "/schedule",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdSessionTypesRouteRoute =
  UserManageEditionIdSessionTypesRouteRouteImport.update({
    id: "/session-types",
    path: "/session-types",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdSessionsRouteRoute =
  UserManageEditionIdSessionsRouteRouteImport.update({
    id: "/sessions",
    path: "/sessions",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdSettingsRouteRoute =
  UserManageEditionIdSettingsRouteRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdSubmissionFormRouteRoute =
  UserManageEditionIdSubmissionFormRouteRouteImport.update({
    id: "/submission-form",
    path: "/submission-form",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdTracksRouteRoute =
  UserManageEditionIdTracksRouteRouteImport.update({
    id: "/tracks",
    path: "/tracks",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdVenuesRouteRoute =
  UserManageEditionIdVenuesRouteRouteImport.update({
    id: "/venues",
    path: "/venues",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserTeamsEditTeamIdRoute = UserTeamsEditTeamIdRouteImport.update({
  id: "/edit/$teamId",
  path: "/edit/$teamId",
  getParentRoute: () => UserTeamsRouteRoute,
} as any);
const UserPublicEditionsEditionIdProfileRoute =
  UserPublicEditionsEditionIdProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => UserPublicEditionsEditionIdRouteRoute,
  } as any);
const UserManageEditionIdCustomFieldsIndexRoute =
  UserManageEditionIdCustomFieldsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdCustomFieldsRouteRoute,
  } as any);
const UserManageEditionIdCustomFieldsCreateRoute =
  UserManageEditionIdCustomFieldsCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => UserManageEditionIdCustomFieldsRouteRoute,
  } as any);
const UserManageEditionIdHostsIndexRoute =
  UserManageEditionIdHostsIndexRouteImport.update({
    id: "/hosts/",
    path: "/hosts/",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdHostsHostIdRoute =
  UserManageEditionIdHostsHostIdRouteImport.update({
    id: "/hosts/$hostId",
    path: "/hosts/$hostId",
    getParentRoute: () => UserManageEditionIdRouteRoute,
  } as any);
const UserManageEditionIdLocationsIndexRoute =
  UserManageEditionIdLocationsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdLocationsRouteRoute,
  } as any);
const UserManageEditionIdLocationsCreateRoute =
  UserManageEditionIdLocationsCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => UserManageEditionIdLocationsRouteRoute,
  } as any);
const UserManageEditionIdScheduleIndexRoute =
  UserManageEditionIdScheduleIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdScheduleRouteRoute,
  } as any);
const UserManageEditionIdScheduleScheduleIdRoute =
  UserManageEditionIdScheduleScheduleIdRouteImport.update({
    id: "/$scheduleId",
    path: "/$scheduleId",
    getParentRoute: () => UserManageEditionIdScheduleRouteRoute,
  } as any);
const UserManageEditionIdSessionTypesListRouteRoute =
  UserManageEditionIdSessionTypesListRouteRouteImport.update({
    id: "/_list",
    getParentRoute: () => UserManageEditionIdSessionTypesRouteRoute,
  } as any);
const UserManageEditionIdSessionsSessionIdRoute =
  UserManageEditionIdSessionsSessionIdRouteImport.update({
    id: "/$sessionId",
    path: "/$sessionId",
    getParentRoute: () => UserManageEditionIdSessionsRouteRoute,
  } as any);
const UserManageEditionIdSessionsListRouteRoute =
  UserManageEditionIdSessionsListRouteRouteImport.update({
    id: "/_list",
    getParentRoute: () => UserManageEditionIdSessionsRouteRoute,
  } as any);
const UserManageEditionIdSessionsCreateRoute =
  UserManageEditionIdSessionsCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => UserManageEditionIdSessionsRouteRoute,
  } as any);
const UserManageEditionIdSubmissionFormIndexRoute =
  UserManageEditionIdSubmissionFormIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdSubmissionFormRouteRoute,
  } as any);
const UserManageEditionIdSubmissionFormMoreInfoRoute =
  UserManageEditionIdSubmissionFormMoreInfoRouteImport.update({
    id: "/more-info",
    path: "/more-info",
    getParentRoute: () => UserManageEditionIdSubmissionFormRouteRoute,
  } as any);
const UserManageEditionIdSubmissionFormProfileRoute =
  UserManageEditionIdSubmissionFormProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => UserManageEditionIdSubmissionFormRouteRoute,
  } as any);
const UserManageEditionIdSubmissionFormSessionRoute =
  UserManageEditionIdSubmissionFormSessionRouteImport.update({
    id: "/session",
    path: "/session",
    getParentRoute: () => UserManageEditionIdSubmissionFormRouteRoute,
  } as any);
const UserManageEditionIdTracksListRouteRoute =
  UserManageEditionIdTracksListRouteRouteImport.update({
    id: "/_list",
    getParentRoute: () => UserManageEditionIdTracksRouteRoute,
  } as any);
const UserManageEditionIdVenuesIndexRoute =
  UserManageEditionIdVenuesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdVenuesRouteRoute,
  } as any);
const UserManageEditionIdVenuesCreateRoute =
  UserManageEditionIdVenuesCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => UserManageEditionIdVenuesRouteRoute,
  } as any);
const UserPublicEditionsEditionIdSessionsIndexRoute =
  UserPublicEditionsEditionIdSessionsIndexRouteImport.update({
    id: "/sessions/",
    path: "/sessions/",
    getParentRoute: () => UserPublicEditionsEditionIdRouteRoute,
  } as any);
const UserPublicEditionsEditionIdSessionsCreateRoute =
  UserPublicEditionsEditionIdSessionsCreateRouteImport.update({
    id: "/sessions/create",
    path: "/sessions/create",
    getParentRoute: () => UserPublicEditionsEditionIdRouteRoute,
  } as any);
const UserManageEditionIdCustomFieldsEditCustomFieldIdRoute =
  UserManageEditionIdCustomFieldsEditCustomFieldIdRouteImport.update({
    id: "/edit/$customFieldId",
    path: "/edit/$customFieldId",
    getParentRoute: () => UserManageEditionIdCustomFieldsRouteRoute,
  } as any);
const UserManageEditionIdLocationsEditLocationIdRoute =
  UserManageEditionIdLocationsEditLocationIdRouteImport.update({
    id: "/edit/$locationId",
    path: "/edit/$locationId",
    getParentRoute: () => UserManageEditionIdLocationsRouteRoute,
  } as any);
const UserManageEditionIdSessionTypesListIndexRoute =
  UserManageEditionIdSessionTypesListIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdSessionTypesListRouteRoute,
  } as any);
const UserManageEditionIdSessionTypesListCreateRoute =
  UserManageEditionIdSessionTypesListCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => UserManageEditionIdSessionTypesListRouteRoute,
  } as any);
const UserManageEditionIdSessionsListIndexRoute =
  UserManageEditionIdSessionsListIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdSessionsListRouteRoute,
  } as any);
const UserManageEditionIdTracksListIndexRoute =
  UserManageEditionIdTracksListIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => UserManageEditionIdTracksListRouteRoute,
  } as any);
const UserManageEditionIdTracksListCreateRoute =
  UserManageEditionIdTracksListCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => UserManageEditionIdTracksListRouteRoute,
  } as any);
const UserManageEditionIdVenuesEditVenueIdRoute =
  UserManageEditionIdVenuesEditVenueIdRouteImport.update({
    id: "/edit/$venueId",
    path: "/edit/$venueId",
    getParentRoute: () => UserManageEditionIdVenuesRouteRoute,
  } as any);
const UserPublicEditionsEditionIdSessionsSessionIdIndexRoute =
  UserPublicEditionsEditionIdSessionsSessionIdIndexRouteImport.update({
    id: "/sessions/$sessionId/",
    path: "/sessions/$sessionId/",
    getParentRoute: () => UserPublicEditionsEditionIdRouteRoute,
  } as any);
const UserPublicEditionsEditionIdSessionsSessionIdEditRoute =
  UserPublicEditionsEditionIdSessionsSessionIdEditRouteImport.update({
    id: "/sessions/$sessionId/edit",
    path: "/sessions/$sessionId/edit",
    getParentRoute: () => UserPublicEditionsEditionIdRouteRoute,
  } as any);
const UserManageEditionIdSessionTypesListEditSessionTypeIdRoute =
  UserManageEditionIdSessionTypesListEditSessionTypeIdRouteImport.update({
    id: "/edit/$sessionTypeId",
    path: "/edit/$sessionTypeId",
    getParentRoute: () => UserManageEditionIdSessionTypesListRouteRoute,
  } as any);
const UserManageEditionIdTracksListEditTrackIdRoute =
  UserManageEditionIdTracksListEditTrackIdRouteImport.update({
    id: "/edit/$trackId",
    path: "/edit/$trackId",
    getParentRoute: () => UserManageEditionIdTracksListRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof UserPublicIndexRoute;
  "/create-profile": typeof CreateProfileRoute;
  "/erase-user": typeof UserEraseUserRouteRouteWithChildren;
  "/jobs": typeof UserJobsRouteRouteWithChildren;
  "/manage": typeof UserManageRouteRouteWithChildren;
  "/teams": typeof UserTeamsRouteRouteWithChildren;
  "/manage/$editionId": typeof UserManageEditionIdRouteRouteWithChildren;
  "/accept-host-invite/$code": typeof UserAcceptHostInviteCodeRoute;
  "/accept-team-invite/$code": typeof UserAcceptTeamInviteCodeRoute;
  "/manage/create-edition": typeof UserManageCreateEditionRoute;
  "/erase-user/": typeof UserEraseUserIndexRoute;
  "/manage/": typeof UserManageIndexRoute;
  "/teams/": typeof UserTeamsIndexRoute;
  "/editions/$editionId": typeof UserPublicEditionsEditionIdRouteRouteWithChildren;
  "/manage/$editionId/custom-fields": typeof UserManageEditionIdCustomFieldsRouteRouteWithChildren;
  "/manage/$editionId/locations": typeof UserManageEditionIdLocationsRouteRouteWithChildren;
  "/manage/$editionId/schedule": typeof UserManageEditionIdScheduleRouteRouteWithChildren;
  "/manage/$editionId/session-types": typeof UserManageEditionIdSessionTypesRouteRouteWithChildren;
  "/manage/$editionId/sessions": typeof UserManageEditionIdSessionsRouteRouteWithChildren;
  "/manage/$editionId/settings": typeof UserManageEditionIdSettingsRouteRoute;
  "/manage/$editionId/submission-form": typeof UserManageEditionIdSubmissionFormRouteRouteWithChildren;
  "/manage/$editionId/tracks": typeof UserManageEditionIdTracksRouteRouteWithChildren;
  "/manage/$editionId/venues": typeof UserManageEditionIdVenuesRouteRouteWithChildren;
  "/jobs/$jobId": typeof UserJobsListJobIdRoute;
  "/teams/edit/$teamId": typeof UserTeamsEditTeamIdRoute;
  "/jobs/": typeof UserJobsListIndexRoute;
  "/manage/$editionId/": typeof UserManageEditionIdIndexRoute;
  "/editions/$editionId/profile": typeof UserPublicEditionsEditionIdProfileRoute;
  "/manage/$editionId/custom-fields/create": typeof UserManageEditionIdCustomFieldsCreateRoute;
  "/manage/$editionId/hosts/$hostId": typeof UserManageEditionIdHostsHostIdRoute;
  "/manage/$editionId/locations/create": typeof UserManageEditionIdLocationsCreateRoute;
  "/manage/$editionId/schedule/$scheduleId": typeof UserManageEditionIdScheduleScheduleIdRoute;
  "/manage/$editionId/sessions/$sessionId": typeof UserManageEditionIdSessionsSessionIdRoute;
  "/manage/$editionId/sessions/create": typeof UserManageEditionIdSessionsCreateRoute;
  "/manage/$editionId/submission-form/more-info": typeof UserManageEditionIdSubmissionFormMoreInfoRoute;
  "/manage/$editionId/submission-form/profile": typeof UserManageEditionIdSubmissionFormProfileRoute;
  "/manage/$editionId/submission-form/session": typeof UserManageEditionIdSubmissionFormSessionRoute;
  "/manage/$editionId/venues/create": typeof UserManageEditionIdVenuesCreateRoute;
  "/manage/$editionId/custom-fields/": typeof UserManageEditionIdCustomFieldsIndexRoute;
  "/manage/$editionId/hosts/": typeof UserManageEditionIdHostsIndexRoute;
  "/manage/$editionId/locations/": typeof UserManageEditionIdLocationsIndexRoute;
  "/manage/$editionId/schedule/": typeof UserManageEditionIdScheduleIndexRoute;
  "/manage/$editionId/submission-form/": typeof UserManageEditionIdSubmissionFormIndexRoute;
  "/manage/$editionId/venues/": typeof UserManageEditionIdVenuesIndexRoute;
  "/editions/$editionId/sessions/create": typeof UserPublicEditionsEditionIdSessionsCreateRoute;
  "/manage/$editionId/custom-fields/edit/$customFieldId": typeof UserManageEditionIdCustomFieldsEditCustomFieldIdRoute;
  "/manage/$editionId/locations/edit/$locationId": typeof UserManageEditionIdLocationsEditLocationIdRoute;
  "/manage/$editionId/session-types/create": typeof UserManageEditionIdSessionTypesListCreateRoute;
  "/manage/$editionId/tracks/create": typeof UserManageEditionIdTracksListCreateRoute;
  "/manage/$editionId/venues/edit/$venueId": typeof UserManageEditionIdVenuesEditVenueIdRoute;
  "/editions/$editionId/sessions/": typeof UserPublicEditionsEditionIdSessionsIndexRoute;
  "/manage/$editionId/session-types/": typeof UserManageEditionIdSessionTypesListIndexRoute;
  "/manage/$editionId/sessions/": typeof UserManageEditionIdSessionsListIndexRoute;
  "/manage/$editionId/tracks/": typeof UserManageEditionIdTracksListIndexRoute;
  "/editions/$editionId/sessions/$sessionId/edit": typeof UserPublicEditionsEditionIdSessionsSessionIdEditRoute;
  "/manage/$editionId/session-types/edit/$sessionTypeId": typeof UserManageEditionIdSessionTypesListEditSessionTypeIdRoute;
  "/manage/$editionId/tracks/edit/$trackId": typeof UserManageEditionIdTracksListEditTrackIdRoute;
  "/editions/$editionId/sessions/$sessionId/": typeof UserPublicEditionsEditionIdSessionsSessionIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof UserPublicIndexRoute;
  "/create-profile": typeof CreateProfileRoute;
  "/jobs": typeof UserJobsListIndexRoute;
  "/accept-host-invite/$code": typeof UserAcceptHostInviteCodeRoute;
  "/accept-team-invite/$code": typeof UserAcceptTeamInviteCodeRoute;
  "/manage/create-edition": typeof UserManageCreateEditionRoute;
  "/erase-user": typeof UserEraseUserIndexRoute;
  "/manage": typeof UserManageIndexRoute;
  "/teams": typeof UserTeamsIndexRoute;
  "/editions/$editionId": typeof UserPublicEditionsEditionIdRouteRouteWithChildren;
  "/manage/$editionId/session-types": typeof UserManageEditionIdSessionTypesListIndexRoute;
  "/manage/$editionId/sessions": typeof UserManageEditionIdSessionsListIndexRoute;
  "/manage/$editionId/settings": typeof UserManageEditionIdSettingsRouteRoute;
  "/manage/$editionId/tracks": typeof UserManageEditionIdTracksListIndexRoute;
  "/jobs/$jobId": typeof UserJobsListJobIdRoute;
  "/teams/edit/$teamId": typeof UserTeamsEditTeamIdRoute;
  "/manage/$editionId": typeof UserManageEditionIdIndexRoute;
  "/editions/$editionId/profile": typeof UserPublicEditionsEditionIdProfileRoute;
  "/manage/$editionId/custom-fields/create": typeof UserManageEditionIdCustomFieldsCreateRoute;
  "/manage/$editionId/hosts/$hostId": typeof UserManageEditionIdHostsHostIdRoute;
  "/manage/$editionId/locations/create": typeof UserManageEditionIdLocationsCreateRoute;
  "/manage/$editionId/schedule/$scheduleId": typeof UserManageEditionIdScheduleScheduleIdRoute;
  "/manage/$editionId/sessions/$sessionId": typeof UserManageEditionIdSessionsSessionIdRoute;
  "/manage/$editionId/sessions/create": typeof UserManageEditionIdSessionsCreateRoute;
  "/manage/$editionId/submission-form/more-info": typeof UserManageEditionIdSubmissionFormMoreInfoRoute;
  "/manage/$editionId/submission-form/profile": typeof UserManageEditionIdSubmissionFormProfileRoute;
  "/manage/$editionId/submission-form/session": typeof UserManageEditionIdSubmissionFormSessionRoute;
  "/manage/$editionId/venues/create": typeof UserManageEditionIdVenuesCreateRoute;
  "/manage/$editionId/custom-fields": typeof UserManageEditionIdCustomFieldsIndexRoute;
  "/manage/$editionId/hosts": typeof UserManageEditionIdHostsIndexRoute;
  "/manage/$editionId/locations": typeof UserManageEditionIdLocationsIndexRoute;
  "/manage/$editionId/schedule": typeof UserManageEditionIdScheduleIndexRoute;
  "/manage/$editionId/submission-form": typeof UserManageEditionIdSubmissionFormIndexRoute;
  "/manage/$editionId/venues": typeof UserManageEditionIdVenuesIndexRoute;
  "/editions/$editionId/sessions/create": typeof UserPublicEditionsEditionIdSessionsCreateRoute;
  "/manage/$editionId/custom-fields/edit/$customFieldId": typeof UserManageEditionIdCustomFieldsEditCustomFieldIdRoute;
  "/manage/$editionId/locations/edit/$locationId": typeof UserManageEditionIdLocationsEditLocationIdRoute;
  "/manage/$editionId/session-types/create": typeof UserManageEditionIdSessionTypesListCreateRoute;
  "/manage/$editionId/tracks/create": typeof UserManageEditionIdTracksListCreateRoute;
  "/manage/$editionId/venues/edit/$venueId": typeof UserManageEditionIdVenuesEditVenueIdRoute;
  "/editions/$editionId/sessions": typeof UserPublicEditionsEditionIdSessionsIndexRoute;
  "/editions/$editionId/sessions/$sessionId/edit": typeof UserPublicEditionsEditionIdSessionsSessionIdEditRoute;
  "/manage/$editionId/session-types/edit/$sessionTypeId": typeof UserManageEditionIdSessionTypesListEditSessionTypeIdRoute;
  "/manage/$editionId/tracks/edit/$trackId": typeof UserManageEditionIdTracksListEditTrackIdRoute;
  "/editions/$editionId/sessions/$sessionId": typeof UserPublicEditionsEditionIdSessionsSessionIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_user": typeof UserRouteRouteWithChildren;
  "/create-profile": typeof CreateProfileRoute;
  "/_user/_public": typeof UserPublicRouteRouteWithChildren;
  "/_user/erase-user": typeof UserEraseUserRouteRouteWithChildren;
  "/_user/jobs": typeof UserJobsRouteRouteWithChildren;
  "/_user/manage": typeof UserManageRouteRouteWithChildren;
  "/_user/teams": typeof UserTeamsRouteRouteWithChildren;
  "/_user/jobs/_list": typeof UserJobsListRouteRouteWithChildren;
  "/_user/manage/$editionId": typeof UserManageEditionIdRouteRouteWithChildren;
  "/_user/accept-host-invite/$code": typeof UserAcceptHostInviteCodeRoute;
  "/_user/accept-team-invite/$code": typeof UserAcceptTeamInviteCodeRoute;
  "/_user/manage/create-edition": typeof UserManageCreateEditionRoute;
  "/_user/_public/": typeof UserPublicIndexRoute;
  "/_user/erase-user/": typeof UserEraseUserIndexRoute;
  "/_user/manage/": typeof UserManageIndexRoute;
  "/_user/teams/": typeof UserTeamsIndexRoute;
  "/_user/_public/editions/$editionId": typeof UserPublicEditionsEditionIdRouteRouteWithChildren;
  "/_user/manage/$editionId/custom-fields": typeof UserManageEditionIdCustomFieldsRouteRouteWithChildren;
  "/_user/manage/$editionId/locations": typeof UserManageEditionIdLocationsRouteRouteWithChildren;
  "/_user/manage/$editionId/schedule": typeof UserManageEditionIdScheduleRouteRouteWithChildren;
  "/_user/manage/$editionId/session-types": typeof UserManageEditionIdSessionTypesRouteRouteWithChildren;
  "/_user/manage/$editionId/sessions": typeof UserManageEditionIdSessionsRouteRouteWithChildren;
  "/_user/manage/$editionId/settings": typeof UserManageEditionIdSettingsRouteRoute;
  "/_user/manage/$editionId/submission-form": typeof UserManageEditionIdSubmissionFormRouteRouteWithChildren;
  "/_user/manage/$editionId/tracks": typeof UserManageEditionIdTracksRouteRouteWithChildren;
  "/_user/manage/$editionId/venues": typeof UserManageEditionIdVenuesRouteRouteWithChildren;
  "/_user/jobs/_list/$jobId": typeof UserJobsListJobIdRoute;
  "/_user/teams/edit/$teamId": typeof UserTeamsEditTeamIdRoute;
  "/_user/jobs/_list/": typeof UserJobsListIndexRoute;
  "/_user/manage/$editionId/": typeof UserManageEditionIdIndexRoute;
  "/_user/manage/$editionId/session-types/_list": typeof UserManageEditionIdSessionTypesListRouteRouteWithChildren;
  "/_user/manage/$editionId/sessions/_list": typeof UserManageEditionIdSessionsListRouteRouteWithChildren;
  "/_user/manage/$editionId/tracks/_list": typeof UserManageEditionIdTracksListRouteRouteWithChildren;
  "/_user/_public/editions/$editionId/profile": typeof UserPublicEditionsEditionIdProfileRoute;
  "/_user/manage/$editionId/custom-fields/create": typeof UserManageEditionIdCustomFieldsCreateRoute;
  "/_user/manage/$editionId/hosts/$hostId": typeof UserManageEditionIdHostsHostIdRoute;
  "/_user/manage/$editionId/locations/create": typeof UserManageEditionIdLocationsCreateRoute;
  "/_user/manage/$editionId/schedule/$scheduleId": typeof UserManageEditionIdScheduleScheduleIdRoute;
  "/_user/manage/$editionId/sessions/$sessionId": typeof UserManageEditionIdSessionsSessionIdRoute;
  "/_user/manage/$editionId/sessions/create": typeof UserManageEditionIdSessionsCreateRoute;
  "/_user/manage/$editionId/submission-form/more-info": typeof UserManageEditionIdSubmissionFormMoreInfoRoute;
  "/_user/manage/$editionId/submission-form/profile": typeof UserManageEditionIdSubmissionFormProfileRoute;
  "/_user/manage/$editionId/submission-form/session": typeof UserManageEditionIdSubmissionFormSessionRoute;
  "/_user/manage/$editionId/venues/create": typeof UserManageEditionIdVenuesCreateRoute;
  "/_user/manage/$editionId/custom-fields/": typeof UserManageEditionIdCustomFieldsIndexRoute;
  "/_user/manage/$editionId/hosts/": typeof UserManageEditionIdHostsIndexRoute;
  "/_user/manage/$editionId/locations/": typeof UserManageEditionIdLocationsIndexRoute;
  "/_user/manage/$editionId/schedule/": typeof UserManageEditionIdScheduleIndexRoute;
  "/_user/manage/$editionId/submission-form/": typeof UserManageEditionIdSubmissionFormIndexRoute;
  "/_user/manage/$editionId/venues/": typeof UserManageEditionIdVenuesIndexRoute;
  "/_user/_public/editions/$editionId/sessions/create": typeof UserPublicEditionsEditionIdSessionsCreateRoute;
  "/_user/manage/$editionId/custom-fields/edit/$customFieldId": typeof UserManageEditionIdCustomFieldsEditCustomFieldIdRoute;
  "/_user/manage/$editionId/locations/edit/$locationId": typeof UserManageEditionIdLocationsEditLocationIdRoute;
  "/_user/manage/$editionId/session-types/_list/create": typeof UserManageEditionIdSessionTypesListCreateRoute;
  "/_user/manage/$editionId/tracks/_list/create": typeof UserManageEditionIdTracksListCreateRoute;
  "/_user/manage/$editionId/venues/edit/$venueId": typeof UserManageEditionIdVenuesEditVenueIdRoute;
  "/_user/_public/editions/$editionId/sessions/": typeof UserPublicEditionsEditionIdSessionsIndexRoute;
  "/_user/manage/$editionId/session-types/_list/": typeof UserManageEditionIdSessionTypesListIndexRoute;
  "/_user/manage/$editionId/sessions/_list/": typeof UserManageEditionIdSessionsListIndexRoute;
  "/_user/manage/$editionId/tracks/_list/": typeof UserManageEditionIdTracksListIndexRoute;
  "/_user/_public/editions/$editionId/sessions/$sessionId/edit": typeof UserPublicEditionsEditionIdSessionsSessionIdEditRoute;
  "/_user/manage/$editionId/session-types/_list/edit/$sessionTypeId": typeof UserManageEditionIdSessionTypesListEditSessionTypeIdRoute;
  "/_user/manage/$editionId/tracks/_list/edit/$trackId": typeof UserManageEditionIdTracksListEditTrackIdRoute;
  "/_user/_public/editions/$editionId/sessions/$sessionId/": typeof UserPublicEditionsEditionIdSessionsSessionIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/create-profile"
    | "/erase-user"
    | "/jobs"
    | "/manage"
    | "/teams"
    | "/manage/$editionId"
    | "/accept-host-invite/$code"
    | "/accept-team-invite/$code"
    | "/manage/create-edition"
    | "/erase-user/"
    | "/manage/"
    | "/teams/"
    | "/editions/$editionId"
    | "/manage/$editionId/custom-fields"
    | "/manage/$editionId/locations"
    | "/manage/$editionId/schedule"
    | "/manage/$editionId/session-types"
    | "/manage/$editionId/sessions"
    | "/manage/$editionId/settings"
    | "/manage/$editionId/submission-form"
    | "/manage/$editionId/tracks"
    | "/manage/$editionId/venues"
    | "/jobs/$jobId"
    | "/teams/edit/$teamId"
    | "/jobs/"
    | "/manage/$editionId/"
    | "/editions/$editionId/profile"
    | "/manage/$editionId/custom-fields/create"
    | "/manage/$editionId/hosts/$hostId"
    | "/manage/$editionId/locations/create"
    | "/manage/$editionId/schedule/$scheduleId"
    | "/manage/$editionId/sessions/$sessionId"
    | "/manage/$editionId/sessions/create"
    | "/manage/$editionId/submission-form/more-info"
    | "/manage/$editionId/submission-form/profile"
    | "/manage/$editionId/submission-form/session"
    | "/manage/$editionId/venues/create"
    | "/manage/$editionId/custom-fields/"
    | "/manage/$editionId/hosts/"
    | "/manage/$editionId/locations/"
    | "/manage/$editionId/schedule/"
    | "/manage/$editionId/submission-form/"
    | "/manage/$editionId/venues/"
    | "/editions/$editionId/sessions/create"
    | "/manage/$editionId/custom-fields/edit/$customFieldId"
    | "/manage/$editionId/locations/edit/$locationId"
    | "/manage/$editionId/session-types/create"
    | "/manage/$editionId/tracks/create"
    | "/manage/$editionId/venues/edit/$venueId"
    | "/editions/$editionId/sessions/"
    | "/manage/$editionId/session-types/"
    | "/manage/$editionId/sessions/"
    | "/manage/$editionId/tracks/"
    | "/editions/$editionId/sessions/$sessionId/edit"
    | "/manage/$editionId/session-types/edit/$sessionTypeId"
    | "/manage/$editionId/tracks/edit/$trackId"
    | "/editions/$editionId/sessions/$sessionId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/create-profile"
    | "/jobs"
    | "/accept-host-invite/$code"
    | "/accept-team-invite/$code"
    | "/manage/create-edition"
    | "/erase-user"
    | "/manage"
    | "/teams"
    | "/editions/$editionId"
    | "/manage/$editionId/session-types"
    | "/manage/$editionId/sessions"
    | "/manage/$editionId/settings"
    | "/manage/$editionId/tracks"
    | "/jobs/$jobId"
    | "/teams/edit/$teamId"
    | "/manage/$editionId"
    | "/editions/$editionId/profile"
    | "/manage/$editionId/custom-fields/create"
    | "/manage/$editionId/hosts/$hostId"
    | "/manage/$editionId/locations/create"
    | "/manage/$editionId/schedule/$scheduleId"
    | "/manage/$editionId/sessions/$sessionId"
    | "/manage/$editionId/sessions/create"
    | "/manage/$editionId/submission-form/more-info"
    | "/manage/$editionId/submission-form/profile"
    | "/manage/$editionId/submission-form/session"
    | "/manage/$editionId/venues/create"
    | "/manage/$editionId/custom-fields"
    | "/manage/$editionId/hosts"
    | "/manage/$editionId/locations"
    | "/manage/$editionId/schedule"
    | "/manage/$editionId/submission-form"
    | "/manage/$editionId/venues"
    | "/editions/$editionId/sessions/create"
    | "/manage/$editionId/custom-fields/edit/$customFieldId"
    | "/manage/$editionId/locations/edit/$locationId"
    | "/manage/$editionId/session-types/create"
    | "/manage/$editionId/tracks/create"
    | "/manage/$editionId/venues/edit/$venueId"
    | "/editions/$editionId/sessions"
    | "/editions/$editionId/sessions/$sessionId/edit"
    | "/manage/$editionId/session-types/edit/$sessionTypeId"
    | "/manage/$editionId/tracks/edit/$trackId"
    | "/editions/$editionId/sessions/$sessionId";
  id:
    | "__root__"
    | "/_user"
    | "/create-profile"
    | "/_user/_public"
    | "/_user/erase-user"
    | "/_user/jobs"
    | "/_user/manage"
    | "/_user/teams"
    | "/_user/jobs/_list"
    | "/_user/manage/$editionId"
    | "/_user/accept-host-invite/$code"
    | "/_user/accept-team-invite/$code"
    | "/_user/manage/create-edition"
    | "/_user/_public/"
    | "/_user/erase-user/"
    | "/_user/manage/"
    | "/_user/teams/"
    | "/_user/_public/editions/$editionId"
    | "/_user/manage/$editionId/custom-fields"
    | "/_user/manage/$editionId/locations"
    | "/_user/manage/$editionId/schedule"
    | "/_user/manage/$editionId/session-types"
    | "/_user/manage/$editionId/sessions"
    | "/_user/manage/$editionId/settings"
    | "/_user/manage/$editionId/submission-form"
    | "/_user/manage/$editionId/tracks"
    | "/_user/manage/$editionId/venues"
    | "/_user/jobs/_list/$jobId"
    | "/_user/teams/edit/$teamId"
    | "/_user/jobs/_list/"
    | "/_user/manage/$editionId/"
    | "/_user/manage/$editionId/session-types/_list"
    | "/_user/manage/$editionId/sessions/_list"
    | "/_user/manage/$editionId/tracks/_list"
    | "/_user/_public/editions/$editionId/profile"
    | "/_user/manage/$editionId/custom-fields/create"
    | "/_user/manage/$editionId/hosts/$hostId"
    | "/_user/manage/$editionId/locations/create"
    | "/_user/manage/$editionId/schedule/$scheduleId"
    | "/_user/manage/$editionId/sessions/$sessionId"
    | "/_user/manage/$editionId/sessions/create"
    | "/_user/manage/$editionId/submission-form/more-info"
    | "/_user/manage/$editionId/submission-form/profile"
    | "/_user/manage/$editionId/submission-form/session"
    | "/_user/manage/$editionId/venues/create"
    | "/_user/manage/$editionId/custom-fields/"
    | "/_user/manage/$editionId/hosts/"
    | "/_user/manage/$editionId/locations/"
    | "/_user/manage/$editionId/schedule/"
    | "/_user/manage/$editionId/submission-form/"
    | "/_user/manage/$editionId/venues/"
    | "/_user/_public/editions/$editionId/sessions/create"
    | "/_user/manage/$editionId/custom-fields/edit/$customFieldId"
    | "/_user/manage/$editionId/locations/edit/$locationId"
    | "/_user/manage/$editionId/session-types/_list/create"
    | "/_user/manage/$editionId/tracks/_list/create"
    | "/_user/manage/$editionId/venues/edit/$venueId"
    | "/_user/_public/editions/$editionId/sessions/"
    | "/_user/manage/$editionId/session-types/_list/"
    | "/_user/manage/$editionId/sessions/_list/"
    | "/_user/manage/$editionId/tracks/_list/"
    | "/_user/_public/editions/$editionId/sessions/$sessionId/edit"
    | "/_user/manage/$editionId/session-types/_list/edit/$sessionTypeId"
    | "/_user/manage/$editionId/tracks/_list/edit/$trackId"
    | "/_user/_public/editions/$editionId/sessions/$sessionId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  UserRouteRoute: typeof UserRouteRouteWithChildren;
  CreateProfileRoute: typeof CreateProfileRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_user": {
      id: "/_user";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof UserRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create-profile": {
      id: "/create-profile";
      path: "/create-profile";
      fullPath: "/create-profile";
      preLoaderRoute: typeof CreateProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_user/_public": {
      id: "/_user/_public";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof UserPublicRouteRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/erase-user": {
      id: "/_user/erase-user";
      path: "/erase-user";
      fullPath: "/erase-user";
      preLoaderRoute: typeof UserEraseUserRouteRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/jobs": {
      id: "/_user/jobs";
      path: "/jobs";
      fullPath: "/jobs";
      preLoaderRoute: typeof UserJobsRouteRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/manage": {
      id: "/_user/manage";
      path: "/manage";
      fullPath: "/manage";
      preLoaderRoute: typeof UserManageRouteRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/teams": {
      id: "/_user/teams";
      path: "/teams";
      fullPath: "/teams";
      preLoaderRoute: typeof UserTeamsRouteRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/_public/": {
      id: "/_user/_public/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof UserPublicIndexRouteImport;
      parentRoute: typeof UserPublicRouteRoute;
    };
    "/_user/accept-host-invite/$code": {
      id: "/_user/accept-host-invite/$code";
      path: "/accept-host-invite/$code";
      fullPath: "/accept-host-invite/$code";
      preLoaderRoute: typeof UserAcceptHostInviteCodeRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/accept-team-invite/$code": {
      id: "/_user/accept-team-invite/$code";
      path: "/accept-team-invite/$code";
      fullPath: "/accept-team-invite/$code";
      preLoaderRoute: typeof UserAcceptTeamInviteCodeRouteImport;
      parentRoute: typeof UserRouteRoute;
    };
    "/_user/erase-user/": {
      id: "/_user/erase-user/";
      path: "/";
      fullPath: "/erase-user/";
      preLoaderRoute: typeof UserEraseUserIndexRouteImport;
      parentRoute: typeof UserEraseUserRouteRoute;
    };
    "/_user/jobs/_list": {
      id: "/_user/jobs/_list";
      path: "";
      fullPath: "/jobs";
      preLoaderRoute: typeof UserJobsListRouteRouteImport;
      parentRoute: typeof UserJobsRouteRoute;
    };
    "/_user/manage/": {
      id: "/_user/manage/";
      path: "/";
      fullPath: "/manage/";
      preLoaderRoute: typeof UserManageIndexRouteImport;
      parentRoute: typeof UserManageRouteRoute;
    };
    "/_user/manage/$editionId": {
      id: "/_user/manage/$editionId";
      path: "/$editionId";
      fullPath: "/manage/$editionId";
      preLoaderRoute: typeof UserManageEditionIdRouteRouteImport;
      parentRoute: typeof UserManageRouteRoute;
    };
    "/_user/manage/create-edition": {
      id: "/_user/manage/create-edition";
      path: "/create-edition";
      fullPath: "/manage/create-edition";
      preLoaderRoute: typeof UserManageCreateEditionRouteImport;
      parentRoute: typeof UserManageRouteRoute;
    };
    "/_user/teams/": {
      id: "/_user/teams/";
      path: "/";
      fullPath: "/teams/";
      preLoaderRoute: typeof UserTeamsIndexRouteImport;
      parentRoute: typeof UserTeamsRouteRoute;
    };
    "/_user/_public/editions/$editionId": {
      id: "/_user/_public/editions/$editionId";
      path: "/editions/$editionId";
      fullPath: "/editions/$editionId";
      preLoaderRoute: typeof UserPublicEditionsEditionIdRouteRouteImport;
      parentRoute: typeof UserPublicRouteRoute;
    };
    "/_user/jobs/_list/": {
      id: "/_user/jobs/_list/";
      path: "/";
      fullPath: "/jobs/";
      preLoaderRoute: typeof UserJobsListIndexRouteImport;
      parentRoute: typeof UserJobsListRouteRoute;
    };
    "/_user/jobs/_list/$jobId": {
      id: "/_user/jobs/_list/$jobId";
      path: "/$jobId";
      fullPath: "/jobs/$jobId";
      preLoaderRoute: typeof UserJobsListJobIdRouteImport;
      parentRoute: typeof UserJobsListRouteRoute;
    };
    "/_user/manage/$editionId/": {
      id: "/_user/manage/$editionId/";
      path: "/";
      fullPath: "/manage/$editionId/";
      preLoaderRoute: typeof UserManageEditionIdIndexRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/custom-fields": {
      id: "/_user/manage/$editionId/custom-fields";
      path: "/custom-fields";
      fullPath: "/manage/$editionId/custom-fields";
      preLoaderRoute: typeof UserManageEditionIdCustomFieldsRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/locations": {
      id: "/_user/manage/$editionId/locations";
      path: "/locations";
      fullPath: "/manage/$editionId/locations";
      preLoaderRoute: typeof UserManageEditionIdLocationsRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/schedule": {
      id: "/_user/manage/$editionId/schedule";
      path: "/schedule";
      fullPath: "/manage/$editionId/schedule";
      preLoaderRoute: typeof UserManageEditionIdScheduleRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/session-types": {
      id: "/_user/manage/$editionId/session-types";
      path: "/session-types";
      fullPath: "/manage/$editionId/session-types";
      preLoaderRoute: typeof UserManageEditionIdSessionTypesRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/sessions": {
      id: "/_user/manage/$editionId/sessions";
      path: "/sessions";
      fullPath: "/manage/$editionId/sessions";
      preLoaderRoute: typeof UserManageEditionIdSessionsRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/settings": {
      id: "/_user/manage/$editionId/settings";
      path: "/settings";
      fullPath: "/manage/$editionId/settings";
      preLoaderRoute: typeof UserManageEditionIdSettingsRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/submission-form": {
      id: "/_user/manage/$editionId/submission-form";
      path: "/submission-form";
      fullPath: "/manage/$editionId/submission-form";
      preLoaderRoute: typeof UserManageEditionIdSubmissionFormRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/tracks": {
      id: "/_user/manage/$editionId/tracks";
      path: "/tracks";
      fullPath: "/manage/$editionId/tracks";
      preLoaderRoute: typeof UserManageEditionIdTracksRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/venues": {
      id: "/_user/manage/$editionId/venues";
      path: "/venues";
      fullPath: "/manage/$editionId/venues";
      preLoaderRoute: typeof UserManageEditionIdVenuesRouteRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/teams/edit/$teamId": {
      id: "/_user/teams/edit/$teamId";
      path: "/edit/$teamId";
      fullPath: "/teams/edit/$teamId";
      preLoaderRoute: typeof UserTeamsEditTeamIdRouteImport;
      parentRoute: typeof UserTeamsRouteRoute;
    };
    "/_user/_public/editions/$editionId/profile": {
      id: "/_user/_public/editions/$editionId/profile";
      path: "/profile";
      fullPath: "/editions/$editionId/profile";
      preLoaderRoute: typeof UserPublicEditionsEditionIdProfileRouteImport;
      parentRoute: typeof UserPublicEditionsEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/custom-fields/": {
      id: "/_user/manage/$editionId/custom-fields/";
      path: "/";
      fullPath: "/manage/$editionId/custom-fields/";
      preLoaderRoute: typeof UserManageEditionIdCustomFieldsIndexRouteImport;
      parentRoute: typeof UserManageEditionIdCustomFieldsRouteRoute;
    };
    "/_user/manage/$editionId/custom-fields/create": {
      id: "/_user/manage/$editionId/custom-fields/create";
      path: "/create";
      fullPath: "/manage/$editionId/custom-fields/create";
      preLoaderRoute: typeof UserManageEditionIdCustomFieldsCreateRouteImport;
      parentRoute: typeof UserManageEditionIdCustomFieldsRouteRoute;
    };
    "/_user/manage/$editionId/hosts/": {
      id: "/_user/manage/$editionId/hosts/";
      path: "/hosts";
      fullPath: "/manage/$editionId/hosts/";
      preLoaderRoute: typeof UserManageEditionIdHostsIndexRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/hosts/$hostId": {
      id: "/_user/manage/$editionId/hosts/$hostId";
      path: "/hosts/$hostId";
      fullPath: "/manage/$editionId/hosts/$hostId";
      preLoaderRoute: typeof UserManageEditionIdHostsHostIdRouteImport;
      parentRoute: typeof UserManageEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/locations/": {
      id: "/_user/manage/$editionId/locations/";
      path: "/";
      fullPath: "/manage/$editionId/locations/";
      preLoaderRoute: typeof UserManageEditionIdLocationsIndexRouteImport;
      parentRoute: typeof UserManageEditionIdLocationsRouteRoute;
    };
    "/_user/manage/$editionId/locations/create": {
      id: "/_user/manage/$editionId/locations/create";
      path: "/create";
      fullPath: "/manage/$editionId/locations/create";
      preLoaderRoute: typeof UserManageEditionIdLocationsCreateRouteImport;
      parentRoute: typeof UserManageEditionIdLocationsRouteRoute;
    };
    "/_user/manage/$editionId/schedule/": {
      id: "/_user/manage/$editionId/schedule/";
      path: "/";
      fullPath: "/manage/$editionId/schedule/";
      preLoaderRoute: typeof UserManageEditionIdScheduleIndexRouteImport;
      parentRoute: typeof UserManageEditionIdScheduleRouteRoute;
    };
    "/_user/manage/$editionId/schedule/$scheduleId": {
      id: "/_user/manage/$editionId/schedule/$scheduleId";
      path: "/$scheduleId";
      fullPath: "/manage/$editionId/schedule/$scheduleId";
      preLoaderRoute: typeof UserManageEditionIdScheduleScheduleIdRouteImport;
      parentRoute: typeof UserManageEditionIdScheduleRouteRoute;
    };
    "/_user/manage/$editionId/session-types/_list": {
      id: "/_user/manage/$editionId/session-types/_list";
      path: "";
      fullPath: "/manage/$editionId/session-types";
      preLoaderRoute: typeof UserManageEditionIdSessionTypesListRouteRouteImport;
      parentRoute: typeof UserManageEditionIdSessionTypesRouteRoute;
    };
    "/_user/manage/$editionId/sessions/$sessionId": {
      id: "/_user/manage/$editionId/sessions/$sessionId";
      path: "/$sessionId";
      fullPath: "/manage/$editionId/sessions/$sessionId";
      preLoaderRoute: typeof UserManageEditionIdSessionsSessionIdRouteImport;
      parentRoute: typeof UserManageEditionIdSessionsRouteRoute;
    };
    "/_user/manage/$editionId/sessions/_list": {
      id: "/_user/manage/$editionId/sessions/_list";
      path: "";
      fullPath: "/manage/$editionId/sessions";
      preLoaderRoute: typeof UserManageEditionIdSessionsListRouteRouteImport;
      parentRoute: typeof UserManageEditionIdSessionsRouteRoute;
    };
    "/_user/manage/$editionId/sessions/create": {
      id: "/_user/manage/$editionId/sessions/create";
      path: "/create";
      fullPath: "/manage/$editionId/sessions/create";
      preLoaderRoute: typeof UserManageEditionIdSessionsCreateRouteImport;
      parentRoute: typeof UserManageEditionIdSessionsRouteRoute;
    };
    "/_user/manage/$editionId/submission-form/": {
      id: "/_user/manage/$editionId/submission-form/";
      path: "/";
      fullPath: "/manage/$editionId/submission-form/";
      preLoaderRoute: typeof UserManageEditionIdSubmissionFormIndexRouteImport;
      parentRoute: typeof UserManageEditionIdSubmissionFormRouteRoute;
    };
    "/_user/manage/$editionId/submission-form/more-info": {
      id: "/_user/manage/$editionId/submission-form/more-info";
      path: "/more-info";
      fullPath: "/manage/$editionId/submission-form/more-info";
      preLoaderRoute: typeof UserManageEditionIdSubmissionFormMoreInfoRouteImport;
      parentRoute: typeof UserManageEditionIdSubmissionFormRouteRoute;
    };
    "/_user/manage/$editionId/submission-form/profile": {
      id: "/_user/manage/$editionId/submission-form/profile";
      path: "/profile";
      fullPath: "/manage/$editionId/submission-form/profile";
      preLoaderRoute: typeof UserManageEditionIdSubmissionFormProfileRouteImport;
      parentRoute: typeof UserManageEditionIdSubmissionFormRouteRoute;
    };
    "/_user/manage/$editionId/submission-form/session": {
      id: "/_user/manage/$editionId/submission-form/session";
      path: "/session";
      fullPath: "/manage/$editionId/submission-form/session";
      preLoaderRoute: typeof UserManageEditionIdSubmissionFormSessionRouteImport;
      parentRoute: typeof UserManageEditionIdSubmissionFormRouteRoute;
    };
    "/_user/manage/$editionId/tracks/_list": {
      id: "/_user/manage/$editionId/tracks/_list";
      path: "";
      fullPath: "/manage/$editionId/tracks";
      preLoaderRoute: typeof UserManageEditionIdTracksListRouteRouteImport;
      parentRoute: typeof UserManageEditionIdTracksRouteRoute;
    };
    "/_user/manage/$editionId/venues/": {
      id: "/_user/manage/$editionId/venues/";
      path: "/";
      fullPath: "/manage/$editionId/venues/";
      preLoaderRoute: typeof UserManageEditionIdVenuesIndexRouteImport;
      parentRoute: typeof UserManageEditionIdVenuesRouteRoute;
    };
    "/_user/manage/$editionId/venues/create": {
      id: "/_user/manage/$editionId/venues/create";
      path: "/create";
      fullPath: "/manage/$editionId/venues/create";
      preLoaderRoute: typeof UserManageEditionIdVenuesCreateRouteImport;
      parentRoute: typeof UserManageEditionIdVenuesRouteRoute;
    };
    "/_user/_public/editions/$editionId/sessions/": {
      id: "/_user/_public/editions/$editionId/sessions/";
      path: "/sessions";
      fullPath: "/editions/$editionId/sessions/";
      preLoaderRoute: typeof UserPublicEditionsEditionIdSessionsIndexRouteImport;
      parentRoute: typeof UserPublicEditionsEditionIdRouteRoute;
    };
    "/_user/_public/editions/$editionId/sessions/create": {
      id: "/_user/_public/editions/$editionId/sessions/create";
      path: "/sessions/create";
      fullPath: "/editions/$editionId/sessions/create";
      preLoaderRoute: typeof UserPublicEditionsEditionIdSessionsCreateRouteImport;
      parentRoute: typeof UserPublicEditionsEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/custom-fields/edit/$customFieldId": {
      id: "/_user/manage/$editionId/custom-fields/edit/$customFieldId";
      path: "/edit/$customFieldId";
      fullPath: "/manage/$editionId/custom-fields/edit/$customFieldId";
      preLoaderRoute: typeof UserManageEditionIdCustomFieldsEditCustomFieldIdRouteImport;
      parentRoute: typeof UserManageEditionIdCustomFieldsRouteRoute;
    };
    "/_user/manage/$editionId/locations/edit/$locationId": {
      id: "/_user/manage/$editionId/locations/edit/$locationId";
      path: "/edit/$locationId";
      fullPath: "/manage/$editionId/locations/edit/$locationId";
      preLoaderRoute: typeof UserManageEditionIdLocationsEditLocationIdRouteImport;
      parentRoute: typeof UserManageEditionIdLocationsRouteRoute;
    };
    "/_user/manage/$editionId/session-types/_list/": {
      id: "/_user/manage/$editionId/session-types/_list/";
      path: "/";
      fullPath: "/manage/$editionId/session-types/";
      preLoaderRoute: typeof UserManageEditionIdSessionTypesListIndexRouteImport;
      parentRoute: typeof UserManageEditionIdSessionTypesListRouteRoute;
    };
    "/_user/manage/$editionId/session-types/_list/create": {
      id: "/_user/manage/$editionId/session-types/_list/create";
      path: "/create";
      fullPath: "/manage/$editionId/session-types/create";
      preLoaderRoute: typeof UserManageEditionIdSessionTypesListCreateRouteImport;
      parentRoute: typeof UserManageEditionIdSessionTypesListRouteRoute;
    };
    "/_user/manage/$editionId/sessions/_list/": {
      id: "/_user/manage/$editionId/sessions/_list/";
      path: "/";
      fullPath: "/manage/$editionId/sessions/";
      preLoaderRoute: typeof UserManageEditionIdSessionsListIndexRouteImport;
      parentRoute: typeof UserManageEditionIdSessionsListRouteRoute;
    };
    "/_user/manage/$editionId/tracks/_list/": {
      id: "/_user/manage/$editionId/tracks/_list/";
      path: "/";
      fullPath: "/manage/$editionId/tracks/";
      preLoaderRoute: typeof UserManageEditionIdTracksListIndexRouteImport;
      parentRoute: typeof UserManageEditionIdTracksListRouteRoute;
    };
    "/_user/manage/$editionId/tracks/_list/create": {
      id: "/_user/manage/$editionId/tracks/_list/create";
      path: "/create";
      fullPath: "/manage/$editionId/tracks/create";
      preLoaderRoute: typeof UserManageEditionIdTracksListCreateRouteImport;
      parentRoute: typeof UserManageEditionIdTracksListRouteRoute;
    };
    "/_user/manage/$editionId/venues/edit/$venueId": {
      id: "/_user/manage/$editionId/venues/edit/$venueId";
      path: "/edit/$venueId";
      fullPath: "/manage/$editionId/venues/edit/$venueId";
      preLoaderRoute: typeof UserManageEditionIdVenuesEditVenueIdRouteImport;
      parentRoute: typeof UserManageEditionIdVenuesRouteRoute;
    };
    "/_user/_public/editions/$editionId/sessions/$sessionId/": {
      id: "/_user/_public/editions/$editionId/sessions/$sessionId/";
      path: "/sessions/$sessionId";
      fullPath: "/editions/$editionId/sessions/$sessionId/";
      preLoaderRoute: typeof UserPublicEditionsEditionIdSessionsSessionIdIndexRouteImport;
      parentRoute: typeof UserPublicEditionsEditionIdRouteRoute;
    };
    "/_user/_public/editions/$editionId/sessions/$sessionId/edit": {
      id: "/_user/_public/editions/$editionId/sessions/$sessionId/edit";
      path: "/sessions/$sessionId/edit";
      fullPath: "/editions/$editionId/sessions/$sessionId/edit";
      preLoaderRoute: typeof UserPublicEditionsEditionIdSessionsSessionIdEditRouteImport;
      parentRoute: typeof UserPublicEditionsEditionIdRouteRoute;
    };
    "/_user/manage/$editionId/session-types/_list/edit/$sessionTypeId": {
      id: "/_user/manage/$editionId/session-types/_list/edit/$sessionTypeId";
      path: "/edit/$sessionTypeId";
      fullPath: "/manage/$editionId/session-types/edit/$sessionTypeId";
      preLoaderRoute: typeof UserManageEditionIdSessionTypesListEditSessionTypeIdRouteImport;
      parentRoute: typeof UserManageEditionIdSessionTypesListRouteRoute;
    };
    "/_user/manage/$editionId/tracks/_list/edit/$trackId": {
      id: "/_user/manage/$editionId/tracks/_list/edit/$trackId";
      path: "/edit/$trackId";
      fullPath: "/manage/$editionId/tracks/edit/$trackId";
      preLoaderRoute: typeof UserManageEditionIdTracksListEditTrackIdRouteImport;
      parentRoute: typeof UserManageEditionIdTracksListRouteRoute;
    };
  }
}

interface UserPublicEditionsEditionIdRouteRouteChildren {
  UserPublicEditionsEditionIdProfileRoute: typeof UserPublicEditionsEditionIdProfileRoute;
  UserPublicEditionsEditionIdSessionsCreateRoute: typeof UserPublicEditionsEditionIdSessionsCreateRoute;
  UserPublicEditionsEditionIdSessionsIndexRoute: typeof UserPublicEditionsEditionIdSessionsIndexRoute;
  UserPublicEditionsEditionIdSessionsSessionIdEditRoute: typeof UserPublicEditionsEditionIdSessionsSessionIdEditRoute;
  UserPublicEditionsEditionIdSessionsSessionIdIndexRoute: typeof UserPublicEditionsEditionIdSessionsSessionIdIndexRoute;
}

const UserPublicEditionsEditionIdRouteRouteChildren: UserPublicEditionsEditionIdRouteRouteChildren =
  {
    UserPublicEditionsEditionIdProfileRoute:
      UserPublicEditionsEditionIdProfileRoute,
    UserPublicEditionsEditionIdSessionsCreateRoute:
      UserPublicEditionsEditionIdSessionsCreateRoute,
    UserPublicEditionsEditionIdSessionsIndexRoute:
      UserPublicEditionsEditionIdSessionsIndexRoute,
    UserPublicEditionsEditionIdSessionsSessionIdEditRoute:
      UserPublicEditionsEditionIdSessionsSessionIdEditRoute,
    UserPublicEditionsEditionIdSessionsSessionIdIndexRoute:
      UserPublicEditionsEditionIdSessionsSessionIdIndexRoute,
  };

const UserPublicEditionsEditionIdRouteRouteWithChildren =
  UserPublicEditionsEditionIdRouteRoute._addFileChildren(
    UserPublicEditionsEditionIdRouteRouteChildren,
  );

interface UserPublicRouteRouteChildren {
  UserPublicIndexRoute: typeof UserPublicIndexRoute;
  UserPublicEditionsEditionIdRouteRoute: typeof UserPublicEditionsEditionIdRouteRouteWithChildren;
}

const UserPublicRouteRouteChildren: UserPublicRouteRouteChildren = {
  UserPublicIndexRoute: UserPublicIndexRoute,
  UserPublicEditionsEditionIdRouteRoute:
    UserPublicEditionsEditionIdRouteRouteWithChildren,
};

const UserPublicRouteRouteWithChildren = UserPublicRouteRoute._addFileChildren(
  UserPublicRouteRouteChildren,
);

interface UserEraseUserRouteRouteChildren {
  UserEraseUserIndexRoute: typeof UserEraseUserIndexRoute;
}

const UserEraseUserRouteRouteChildren: UserEraseUserRouteRouteChildren = {
  UserEraseUserIndexRoute: UserEraseUserIndexRoute,
};

const UserEraseUserRouteRouteWithChildren =
  UserEraseUserRouteRoute._addFileChildren(UserEraseUserRouteRouteChildren);

interface UserJobsListRouteRouteChildren {
  UserJobsListJobIdRoute: typeof UserJobsListJobIdRoute;
  UserJobsListIndexRoute: typeof UserJobsListIndexRoute;
}

const UserJobsListRouteRouteChildren: UserJobsListRouteRouteChildren = {
  UserJobsListJobIdRoute: UserJobsListJobIdRoute,
  UserJobsListIndexRoute: UserJobsListIndexRoute,
};

const UserJobsListRouteRouteWithChildren =
  UserJobsListRouteRoute._addFileChildren(UserJobsListRouteRouteChildren);

interface UserJobsRouteRouteChildren {
  UserJobsListRouteRoute: typeof UserJobsListRouteRouteWithChildren;
}

const UserJobsRouteRouteChildren: UserJobsRouteRouteChildren = {
  UserJobsListRouteRoute: UserJobsListRouteRouteWithChildren,
};

const UserJobsRouteRouteWithChildren = UserJobsRouteRoute._addFileChildren(
  UserJobsRouteRouteChildren,
);

interface UserManageEditionIdCustomFieldsRouteRouteChildren {
  UserManageEditionIdCustomFieldsCreateRoute: typeof UserManageEditionIdCustomFieldsCreateRoute;
  UserManageEditionIdCustomFieldsIndexRoute: typeof UserManageEditionIdCustomFieldsIndexRoute;
  UserManageEditionIdCustomFieldsEditCustomFieldIdRoute: typeof UserManageEditionIdCustomFieldsEditCustomFieldIdRoute;
}

const UserManageEditionIdCustomFieldsRouteRouteChildren: UserManageEditionIdCustomFieldsRouteRouteChildren =
  {
    UserManageEditionIdCustomFieldsCreateRoute:
      UserManageEditionIdCustomFieldsCreateRoute,
    UserManageEditionIdCustomFieldsIndexRoute:
      UserManageEditionIdCustomFieldsIndexRoute,
    UserManageEditionIdCustomFieldsEditCustomFieldIdRoute:
      UserManageEditionIdCustomFieldsEditCustomFieldIdRoute,
  };

const UserManageEditionIdCustomFieldsRouteRouteWithChildren =
  UserManageEditionIdCustomFieldsRouteRoute._addFileChildren(
    UserManageEditionIdCustomFieldsRouteRouteChildren,
  );

interface UserManageEditionIdLocationsRouteRouteChildren {
  UserManageEditionIdLocationsCreateRoute: typeof UserManageEditionIdLocationsCreateRoute;
  UserManageEditionIdLocationsIndexRoute: typeof UserManageEditionIdLocationsIndexRoute;
  UserManageEditionIdLocationsEditLocationIdRoute: typeof UserManageEditionIdLocationsEditLocationIdRoute;
}

const UserManageEditionIdLocationsRouteRouteChildren: UserManageEditionIdLocationsRouteRouteChildren =
  {
    UserManageEditionIdLocationsCreateRoute:
      UserManageEditionIdLocationsCreateRoute,
    UserManageEditionIdLocationsIndexRoute:
      UserManageEditionIdLocationsIndexRoute,
    UserManageEditionIdLocationsEditLocationIdRoute:
      UserManageEditionIdLocationsEditLocationIdRoute,
  };

const UserManageEditionIdLocationsRouteRouteWithChildren =
  UserManageEditionIdLocationsRouteRoute._addFileChildren(
    UserManageEditionIdLocationsRouteRouteChildren,
  );

interface UserManageEditionIdScheduleRouteRouteChildren {
  UserManageEditionIdScheduleScheduleIdRoute: typeof UserManageEditionIdScheduleScheduleIdRoute;
  UserManageEditionIdScheduleIndexRoute: typeof UserManageEditionIdScheduleIndexRoute;
}

const UserManageEditionIdScheduleRouteRouteChildren: UserManageEditionIdScheduleRouteRouteChildren =
  {
    UserManageEditionIdScheduleScheduleIdRoute:
      UserManageEditionIdScheduleScheduleIdRoute,
    UserManageEditionIdScheduleIndexRoute:
      UserManageEditionIdScheduleIndexRoute,
  };

const UserManageEditionIdScheduleRouteRouteWithChildren =
  UserManageEditionIdScheduleRouteRoute._addFileChildren(
    UserManageEditionIdScheduleRouteRouteChildren,
  );

interface UserManageEditionIdSessionTypesListRouteRouteChildren {
  UserManageEditionIdSessionTypesListCreateRoute: typeof UserManageEditionIdSessionTypesListCreateRoute;
  UserManageEditionIdSessionTypesListIndexRoute: typeof UserManageEditionIdSessionTypesListIndexRoute;
  UserManageEditionIdSessionTypesListEditSessionTypeIdRoute: typeof UserManageEditionIdSessionTypesListEditSessionTypeIdRoute;
}

const UserManageEditionIdSessionTypesListRouteRouteChildren: UserManageEditionIdSessionTypesListRouteRouteChildren =
  {
    UserManageEditionIdSessionTypesListCreateRoute:
      UserManageEditionIdSessionTypesListCreateRoute,
    UserManageEditionIdSessionTypesListIndexRoute:
      UserManageEditionIdSessionTypesListIndexRoute,
    UserManageEditionIdSessionTypesListEditSessionTypeIdRoute:
      UserManageEditionIdSessionTypesListEditSessionTypeIdRoute,
  };

const UserManageEditionIdSessionTypesListRouteRouteWithChildren =
  UserManageEditionIdSessionTypesListRouteRoute._addFileChildren(
    UserManageEditionIdSessionTypesListRouteRouteChildren,
  );

interface UserManageEditionIdSessionTypesRouteRouteChildren {
  UserManageEditionIdSessionTypesListRouteRoute: typeof UserManageEditionIdSessionTypesListRouteRouteWithChildren;
}

const UserManageEditionIdSessionTypesRouteRouteChildren: UserManageEditionIdSessionTypesRouteRouteChildren =
  {
    UserManageEditionIdSessionTypesListRouteRoute:
      UserManageEditionIdSessionTypesListRouteRouteWithChildren,
  };

const UserManageEditionIdSessionTypesRouteRouteWithChildren =
  UserManageEditionIdSessionTypesRouteRoute._addFileChildren(
    UserManageEditionIdSessionTypesRouteRouteChildren,
  );

interface UserManageEditionIdSessionsListRouteRouteChildren {
  UserManageEditionIdSessionsListIndexRoute: typeof UserManageEditionIdSessionsListIndexRoute;
}

const UserManageEditionIdSessionsListRouteRouteChildren: UserManageEditionIdSessionsListRouteRouteChildren =
  {
    UserManageEditionIdSessionsListIndexRoute:
      UserManageEditionIdSessionsListIndexRoute,
  };

const UserManageEditionIdSessionsListRouteRouteWithChildren =
  UserManageEditionIdSessionsListRouteRoute._addFileChildren(
    UserManageEditionIdSessionsListRouteRouteChildren,
  );

interface UserManageEditionIdSessionsRouteRouteChildren {
  UserManageEditionIdSessionsListRouteRoute: typeof UserManageEditionIdSessionsListRouteRouteWithChildren;
  UserManageEditionIdSessionsSessionIdRoute: typeof UserManageEditionIdSessionsSessionIdRoute;
  UserManageEditionIdSessionsCreateRoute: typeof UserManageEditionIdSessionsCreateRoute;
}

const UserManageEditionIdSessionsRouteRouteChildren: UserManageEditionIdSessionsRouteRouteChildren =
  {
    UserManageEditionIdSessionsListRouteRoute:
      UserManageEditionIdSessionsListRouteRouteWithChildren,
    UserManageEditionIdSessionsSessionIdRoute:
      UserManageEditionIdSessionsSessionIdRoute,
    UserManageEditionIdSessionsCreateRoute:
      UserManageEditionIdSessionsCreateRoute,
  };

const UserManageEditionIdSessionsRouteRouteWithChildren =
  UserManageEditionIdSessionsRouteRoute._addFileChildren(
    UserManageEditionIdSessionsRouteRouteChildren,
  );

interface UserManageEditionIdSubmissionFormRouteRouteChildren {
  UserManageEditionIdSubmissionFormMoreInfoRoute: typeof UserManageEditionIdSubmissionFormMoreInfoRoute;
  UserManageEditionIdSubmissionFormProfileRoute: typeof UserManageEditionIdSubmissionFormProfileRoute;
  UserManageEditionIdSubmissionFormSessionRoute: typeof UserManageEditionIdSubmissionFormSessionRoute;
  UserManageEditionIdSubmissionFormIndexRoute: typeof UserManageEditionIdSubmissionFormIndexRoute;
}

const UserManageEditionIdSubmissionFormRouteRouteChildren: UserManageEditionIdSubmissionFormRouteRouteChildren =
  {
    UserManageEditionIdSubmissionFormMoreInfoRoute:
      UserManageEditionIdSubmissionFormMoreInfoRoute,
    UserManageEditionIdSubmissionFormProfileRoute:
      UserManageEditionIdSubmissionFormProfileRoute,
    UserManageEditionIdSubmissionFormSessionRoute:
      UserManageEditionIdSubmissionFormSessionRoute,
    UserManageEditionIdSubmissionFormIndexRoute:
      UserManageEditionIdSubmissionFormIndexRoute,
  };

const UserManageEditionIdSubmissionFormRouteRouteWithChildren =
  UserManageEditionIdSubmissionFormRouteRoute._addFileChildren(
    UserManageEditionIdSubmissionFormRouteRouteChildren,
  );

interface UserManageEditionIdTracksListRouteRouteChildren {
  UserManageEditionIdTracksListCreateRoute: typeof UserManageEditionIdTracksListCreateRoute;
  UserManageEditionIdTracksListIndexRoute: typeof UserManageEditionIdTracksListIndexRoute;
  UserManageEditionIdTracksListEditTrackIdRoute: typeof UserManageEditionIdTracksListEditTrackIdRoute;
}

const UserManageEditionIdTracksListRouteRouteChildren: UserManageEditionIdTracksListRouteRouteChildren =
  {
    UserManageEditionIdTracksListCreateRoute:
      UserManageEditionIdTracksListCreateRoute,
    UserManageEditionIdTracksListIndexRoute:
      UserManageEditionIdTracksListIndexRoute,
    UserManageEditionIdTracksListEditTrackIdRoute:
      UserManageEditionIdTracksListEditTrackIdRoute,
  };

const UserManageEditionIdTracksListRouteRouteWithChildren =
  UserManageEditionIdTracksListRouteRoute._addFileChildren(
    UserManageEditionIdTracksListRouteRouteChildren,
  );

interface UserManageEditionIdTracksRouteRouteChildren {
  UserManageEditionIdTracksListRouteRoute: typeof UserManageEditionIdTracksListRouteRouteWithChildren;
}

const UserManageEditionIdTracksRouteRouteChildren: UserManageEditionIdTracksRouteRouteChildren =
  {
    UserManageEditionIdTracksListRouteRoute:
      UserManageEditionIdTracksListRouteRouteWithChildren,
  };

const UserManageEditionIdTracksRouteRouteWithChildren =
  UserManageEditionIdTracksRouteRoute._addFileChildren(
    UserManageEditionIdTracksRouteRouteChildren,
  );

interface UserManageEditionIdVenuesRouteRouteChildren {
  UserManageEditionIdVenuesCreateRoute: typeof UserManageEditionIdVenuesCreateRoute;
  UserManageEditionIdVenuesIndexRoute: typeof UserManageEditionIdVenuesIndexRoute;
  UserManageEditionIdVenuesEditVenueIdRoute: typeof UserManageEditionIdVenuesEditVenueIdRoute;
}

const UserManageEditionIdVenuesRouteRouteChildren: UserManageEditionIdVenuesRouteRouteChildren =
  {
    UserManageEditionIdVenuesCreateRoute: UserManageEditionIdVenuesCreateRoute,
    UserManageEditionIdVenuesIndexRoute: UserManageEditionIdVenuesIndexRoute,
    UserManageEditionIdVenuesEditVenueIdRoute:
      UserManageEditionIdVenuesEditVenueIdRoute,
  };

const UserManageEditionIdVenuesRouteRouteWithChildren =
  UserManageEditionIdVenuesRouteRoute._addFileChildren(
    UserManageEditionIdVenuesRouteRouteChildren,
  );

interface UserManageEditionIdRouteRouteChildren {
  UserManageEditionIdCustomFieldsRouteRoute: typeof UserManageEditionIdCustomFieldsRouteRouteWithChildren;
  UserManageEditionIdLocationsRouteRoute: typeof UserManageEditionIdLocationsRouteRouteWithChildren;
  UserManageEditionIdScheduleRouteRoute: typeof UserManageEditionIdScheduleRouteRouteWithChildren;
  UserManageEditionIdSessionTypesRouteRoute: typeof UserManageEditionIdSessionTypesRouteRouteWithChildren;
  UserManageEditionIdSessionsRouteRoute: typeof UserManageEditionIdSessionsRouteRouteWithChildren;
  UserManageEditionIdSettingsRouteRoute: typeof UserManageEditionIdSettingsRouteRoute;
  UserManageEditionIdSubmissionFormRouteRoute: typeof UserManageEditionIdSubmissionFormRouteRouteWithChildren;
  UserManageEditionIdTracksRouteRoute: typeof UserManageEditionIdTracksRouteRouteWithChildren;
  UserManageEditionIdVenuesRouteRoute: typeof UserManageEditionIdVenuesRouteRouteWithChildren;
  UserManageEditionIdIndexRoute: typeof UserManageEditionIdIndexRoute;
  UserManageEditionIdHostsHostIdRoute: typeof UserManageEditionIdHostsHostIdRoute;
  UserManageEditionIdHostsIndexRoute: typeof UserManageEditionIdHostsIndexRoute;
}

const UserManageEditionIdRouteRouteChildren: UserManageEditionIdRouteRouteChildren =
  {
    UserManageEditionIdCustomFieldsRouteRoute:
      UserManageEditionIdCustomFieldsRouteRouteWithChildren,
    UserManageEditionIdLocationsRouteRoute:
      UserManageEditionIdLocationsRouteRouteWithChildren,
    UserManageEditionIdScheduleRouteRoute:
      UserManageEditionIdScheduleRouteRouteWithChildren,
    UserManageEditionIdSessionTypesRouteRoute:
      UserManageEditionIdSessionTypesRouteRouteWithChildren,
    UserManageEditionIdSessionsRouteRoute:
      UserManageEditionIdSessionsRouteRouteWithChildren,
    UserManageEditionIdSettingsRouteRoute:
      UserManageEditionIdSettingsRouteRoute,
    UserManageEditionIdSubmissionFormRouteRoute:
      UserManageEditionIdSubmissionFormRouteRouteWithChildren,
    UserManageEditionIdTracksRouteRoute:
      UserManageEditionIdTracksRouteRouteWithChildren,
    UserManageEditionIdVenuesRouteRoute:
      UserManageEditionIdVenuesRouteRouteWithChildren,
    UserManageEditionIdIndexRoute: UserManageEditionIdIndexRoute,
    UserManageEditionIdHostsHostIdRoute: UserManageEditionIdHostsHostIdRoute,
    UserManageEditionIdHostsIndexRoute: UserManageEditionIdHostsIndexRoute,
  };

const UserManageEditionIdRouteRouteWithChildren =
  UserManageEditionIdRouteRoute._addFileChildren(
    UserManageEditionIdRouteRouteChildren,
  );

interface UserManageRouteRouteChildren {
  UserManageEditionIdRouteRoute: typeof UserManageEditionIdRouteRouteWithChildren;
  UserManageCreateEditionRoute: typeof UserManageCreateEditionRoute;
  UserManageIndexRoute: typeof UserManageIndexRoute;
}

const UserManageRouteRouteChildren: UserManageRouteRouteChildren = {
  UserManageEditionIdRouteRoute: UserManageEditionIdRouteRouteWithChildren,
  UserManageCreateEditionRoute: UserManageCreateEditionRoute,
  UserManageIndexRoute: UserManageIndexRoute,
};

const UserManageRouteRouteWithChildren = UserManageRouteRoute._addFileChildren(
  UserManageRouteRouteChildren,
);

interface UserTeamsRouteRouteChildren {
  UserTeamsIndexRoute: typeof UserTeamsIndexRoute;
  UserTeamsEditTeamIdRoute: typeof UserTeamsEditTeamIdRoute;
}

const UserTeamsRouteRouteChildren: UserTeamsRouteRouteChildren = {
  UserTeamsIndexRoute: UserTeamsIndexRoute,
  UserTeamsEditTeamIdRoute: UserTeamsEditTeamIdRoute,
};

const UserTeamsRouteRouteWithChildren = UserTeamsRouteRoute._addFileChildren(
  UserTeamsRouteRouteChildren,
);

interface UserRouteRouteChildren {
  UserPublicRouteRoute: typeof UserPublicRouteRouteWithChildren;
  UserEraseUserRouteRoute: typeof UserEraseUserRouteRouteWithChildren;
  UserJobsRouteRoute: typeof UserJobsRouteRouteWithChildren;
  UserManageRouteRoute: typeof UserManageRouteRouteWithChildren;
  UserTeamsRouteRoute: typeof UserTeamsRouteRouteWithChildren;
  UserAcceptHostInviteCodeRoute: typeof UserAcceptHostInviteCodeRoute;
  UserAcceptTeamInviteCodeRoute: typeof UserAcceptTeamInviteCodeRoute;
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserPublicRouteRoute: UserPublicRouteRouteWithChildren,
  UserEraseUserRouteRoute: UserEraseUserRouteRouteWithChildren,
  UserJobsRouteRoute: UserJobsRouteRouteWithChildren,
  UserManageRouteRoute: UserManageRouteRouteWithChildren,
  UserTeamsRouteRoute: UserTeamsRouteRouteWithChildren,
  UserAcceptHostInviteCodeRoute: UserAcceptHostInviteCodeRoute,
  UserAcceptTeamInviteCodeRoute: UserAcceptTeamInviteCodeRoute,
};

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  UserRouteRoute: UserRouteRouteWithChildren,
  CreateProfileRoute: CreateProfileRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
